/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/* @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = { 
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
 
  tutorialSidebar: [
    'intro', 
	'faqs',
	'how_to',
    {
      type: 'category',
      label: 'Claim a QRLynk',
      items: ['claim/claim_intro','claim/claim_pregenerated','claim/claim_custom'],
    },		
    {
      type: 'category',
      label: 'Registration & Plans',
      items: ['registration/registration','registration/plans'],
    },	
    {
      type: 'category',
      label: 'Create a Page',
      items: ['page/create_page', 'page/sections', 'page/design'],
    },		
    {
      type: 'category',
      label: 'Create a QRLynk',
      items: ['qrlynk/create_qrlynk', 'qrlynk/design', 'qrlynk/static'],
    },	
	{
      type: 'category',
      label: 'QRLynk Management',
      items: ['page/manage','qrlynk/manage'],
    },	
	'support'
  ],
   
   
};

module.exports = sidebars;
